### ISSUE TITLE
Disable sponsored top sites?

### ISSUE THREAD

**Issue by jplock** [loganmarchione/Firefox-tweaks#4]
Not sure if you saw this one:
- https://old.reddit.com/r/firefox/comments/jybx2w/uh_why_is_firefox_showing_me_sponsored_links_in/
- https://www.reddit.com/r/privacytoolsIO/comments/jygrdf/experimental_feature_sponsored_top_sites_in/

Setting `browser.newtabpage.activity-stream.showSponsoredTopSites` to `false` is suppose to remove it

**Comment by loganmarchione** [comment]
@jplock  - I wasn't aware of this, thanks!
